# Generated by Django 2.2.3 on 2019-09-05 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comboproducto',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='myapp.Producto'),
        ),
        migrations.AlterField(
            model_name='detalle_orden_menu',
            name='Orden_Menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleO', to='myapp.Orden_Menu'),
        ),
        migrations.AlterField(
            model_name='detalle_orden_menu',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleP', to='myapp.Producto'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='Contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='myapp.Contacto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='myapp.Categoria'),
        ),
    ]
