# Generated by Django 2.2.3 on 2019-09-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190905_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Edad',
            field=models.IntegerField(),
        ),
    ]
